### ISSUE TITLE
No ROS Tooling for ROS 2 Kilted Kaiju

### ISSUE THREAD

**Issue by knmcguire** [ros-tooling/setup-ros-docker#88]
## Description
** clear and concise description of the bug is **
In another github CI, I wanted to setup ROS tooling for ROS2 kilted

### Expected Behavior
** clear and concise description of what you _expected_ to happen **

For the rostooling image for Kilted to be available in CI

### Actual Behavior
** clear and concise description of what _actually_ happened. include copied logs whenever possible **

```
  /usr/bin/docker pull rostooling/setup-ros-docker:ubuntu-noble-ros-kilted-ros-base-latest
  Error response from daemon: manifest for rostooling/setup-ros-docker:ubuntu-noble-ros-kilted-ros-base-latest not found: manifest unknown: manifest unknown
  Error: Docker pull failed with exit code 1
```

## To Reproduce
** Steps to reproduce the behavior, e.g.
In github action add:

```
      matrix:
        ros_distribution:
          - kilted 
          - rolling
        include:
          - docker_image: rostooling/setup-ros-docker:ubuntu-noble-ros-kilted-ros-base-latest
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-rolling-ros-base-latest
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.docker_image }}
    steps:
    - uses: actions/checkout@v4
```

You'll see the error with kilted but not with rolling

## System (please complete the following information)
 - OS: Ubuntu Noble (ubuntu-latest)
 - ROS 2 Distro: Kilted

** For ROS 2 bugs - please attach a VCS.repos or Dockerfile if possible to help us reproduce the environment **

## Additional context
** Add any other context about the problem here **

Related to PR here of the ros2-rust repos: https://github.com/ros2-rust/ros2_rust/pull/490

Also I noticed that it is missing from the build.yml file:
https://github.com/ros-tooling/setup-ros-docker/blob/abc81c3a6ba0685b76b6ae71eab722199dd4eeba/.github/workflows/build.yml#L75 

but it should exist in [the osrf docker files](https://github.com/osrf/docker_images/blob/master/ros/kilted/ubuntu/noble/ros-base/Dockerfile). Simple matter of just adding it to build.yml?
